#!/usr/bin/env python3
"""Regenerate the site gallery from design/gallery.txt.

The manifest lists the source photos in gallery order (see the comment
block at the top of gallery.txt for the line format). For each entry this
script writes public/img/gallery/gN.jpg (the lightbox image, fitted into
1800x1800) and gN-thumb.jpg (a 678x900 crop for the grid), then rewrites
the gallery cells in public/index.html between the gallery-cells markers.
Stale gN files beyond the manifest length are removed.

Requires ImageMagick (`magick`) on PATH.

Run:  python3 design/gallery.py   (or `make gallery`)
"""

import pathlib
import re
import subprocess
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
PHOTOS = ROOT / "design" / "photos"
MANIFEST = ROOT / "design" / "gallery.txt"
OUT = ROOT / "public" / "img" / "gallery"
INDEX = ROOT / "public" / "index.html"

START = "<!-- gallery-cells:start (generated by design/gallery.py) -->"
END = "<!-- gallery-cells:end -->"

CELL = (
    '      <button class="gallery-cell{wide}" type="button"'
    ' data-full="img/gallery/g{n}.jpg" aria-label="Open photo {n}">'
    '<img src="img/gallery/g{n}-thumb.jpg" alt="{alt}" loading="lazy">'
    "</button>"
)


def parse_manifest():
    """Return the manifest as a list of (source, alt, flags) tuples."""
    entries = []
    for raw in MANIFEST.read_text().splitlines():
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        parts = [p.strip() for p in line.split("|")]
        if len(parts) < 2:
            sys.exit(f"gallery.txt: missing alt text on line: {line}")
        src, alt = parts[0], parts[1]
        flags = set()
        if len(parts) > 2 and parts[2]:
            flags = {f.strip() for f in parts[2].split(",")}
        if not (PHOTOS / src).exists():
            sys.exit(f"gallery.txt: no such photo: design/photos/{src}")
        entries.append((src, alt, flags))
    return entries


def magick(args):
    """Run one ImageMagick command, failing loudly on error."""
    res = subprocess.run(["magick", *args], capture_output=True, text=True, check=False)
    if res.returncode != 0:
        sys.exit(f"magick {' '.join(args)}: {res.stderr.strip()}")


def crop_gravity(flags):
    """Return the thumbnail crop gravity named by a crop= flag, if any."""
    for f in flags:
        if f.startswith("crop="):
            return f.split("=", 1)[1].capitalize()
    return "Center"


def generate_images(entries):
    """Write gN.jpg and gN-thumb.jpg for every manifest entry."""
    OUT.mkdir(parents=True, exist_ok=True)
    for i, (src, _alt, flags) in enumerate(entries, start=1):
        photo = str(PHOTOS / src)
        full = str(OUT / f"g{i}.jpg")
        thumb = str(OUT / f"g{i}-thumb.jpg")
        magick([photo, "-auto-orient", "-resize", "1800x1800>",
                "-quality", "85", full])
        magick([photo, "-auto-orient", "-resize", "678x900^",
                "-gravity", crop_gravity(flags),
                "-extent", "678x900", "-quality", "85", thumb])
        print(f"g{i}  {src}")


def remove_stale(count):
    """Delete gN files left over from a previously longer gallery."""
    for path in OUT.glob("g*.jpg"):
        m = re.match(r"g(\d+)(-thumb)?\.jpg$", path.name)
        if m and int(m.group(1)) > count:
            path.unlink()
            print(f"removed stale {path.name}")


def rewrite_index(entries):
    """Replace the gallery cells in index.html between the markers."""
    html = INDEX.read_text()
    if START not in html or END not in html:
        sys.exit(f"index.html: missing {START} / {END} markers")
    cells = "\n".join(
        CELL.format(
            n=i,
            alt=alt.replace("&", "&amp;").replace('"', "&quot;"),
            wide=" gallery-cell--wide-only" if "wide-only" in flags else "",
        )
        for i, (_src, alt, flags) in enumerate(entries, start=1)
    )
    pre, rest = html.split(START, 1)
    _, post = rest.split(END, 1)
    INDEX.write_text(f"{pre}{START}\n{cells}\n      {END}{post}")


def main():
    entries = parse_manifest()
    generate_images(entries)
    remove_stale(len(entries))
    rewrite_index(entries)
    print(f"gallery: {len(entries)} photos")


if __name__ == "__main__":
    main()
