"""Write platonic/gsd.scad: a great stellated dodecahedron as twenty pyramids.

Start from the icosahedron. The five neighbours of each vertex form a
pentagon; the pentagram drawn through that pentagon has its five outer points
at phi squared times the pentagon's radius, in the directions of the
pentagon's edge midpoints. Those sixty points coincide in fives and are the
twenty vertices of the star. Each star point is then the pyramid over one
icosahedron face with its apex at the vertex on that face's normal.

Run from the repo root:
    python3 platonic/gsd.py
"""

import itertools
import math

PHI = (1 + 5**0.5) / 2


def sub(a, b):
    return tuple(x - y for x, y in zip(a, b))


def add(a, b):
    return tuple(x + y for x, y in zip(a, b))


def mul(a, k):
    return tuple(x * k for x in a)


def dot(a, b):
    return sum(x * y for x, y in zip(a, b))


def norm(a):
    return math.sqrt(dot(a, a))


def unit(a):
    return mul(a, 1 / norm(a))


def cross(a, b):
    return (
        a[1] * b[2] - a[2] * b[1],
        a[2] * b[0] - a[0] * b[2],
        a[0] * b[1] - a[1] * b[0],
    )


def icosahedron():
    pts = []
    for a in (1, -1):
        for b in (1, -1):
            pts += [(0, a, b * PHI), (a, b * PHI, 0), (b * PHI, 0, a)]
    return pts


def dedupe(points, tol=1e-6):
    out = []
    for p in points:
        if not any(norm(sub(p, q)) < tol for q in out):
            out.append(p)
    return out


def star_points(ico, edge):
    outer = []
    for v in ico:
        nb = [w for w in ico if abs(norm(sub(v, w)) - edge) < 1e-6]
        n = unit(v)
        c = mul(n, dot(nb[0], n))
        u = unit(sub(nb[0], c))
        w = cross(n, u)
        nb.sort(key=lambda p: math.atan2(dot(sub(p, c), w), dot(sub(p, c), u)))
        r = norm(sub(nb[0], c))
        for i in range(5):
            m = mul(add(nb[i], nb[(i + 1) % 5]), 0.5)
            outer.append(add(c, mul(unit(sub(m, c)), r * PHI**2)))
    return dedupe(outer)


def main():
    ico = icosahedron()
    edge = min(norm(sub(a, b)) for a, b in itertools.combinations(ico, 2))
    tips = star_points(ico, edge)
    assert len(tips) == 20
    faces = [
        t
        for t in itertools.combinations(range(12), 3)
        if all(
            abs(norm(sub(ico[a], ico[b])) - edge) < 1e-6
            for a, b in itertools.combinations(t, 2)
        )
    ]
    assert len(faces) == 20
    radius = norm(tips[0])
    pyramids = []
    for t in faces:
        c = unit(mul(add(add(ico[t[0]], ico[t[1]]), ico[t[2]]), 1 / 3))
        apex = max(tips, key=lambda v: dot(v, c))
        pyramids.append([ico[t[0]], ico[t[1]], ico[t[2]], apex])

    def fmt(v):
        return "[{:.5f}, {:.5f}, {:.5f}]".format(*(x / radius for x in v))

    lines = [
        "// Great stellated dodecahedron: twenty triangular pyramids on the faces of",
        "// an icosahedron, apexes at the vertices of the enclosing dodecahedron. The",
        "// coordinates span 2 units point to opposite point. Generated by",
        "// platonic/gsd.py; edit that, not this.",
        "",
        "gsd_pyramids = [",
    ]
    lines += ["  [" + ", ".join(fmt(v) for v in p) + "]," for p in pyramids]
    lines += [
        "];",
        "",
        "// span is point to opposite point, mm. below and above cut every point",
        "// whose apex lies further below or above the centre than that fraction of",
        "// the half span, so the star can sit on something, or around a post,",
        "// without spikes in the way.",
        "module gsd(span = 1000, below = 2, above = 2) {",
        "  scale(span / 2) for (p = gsd_pyramids) if (p[3][2] > -below && p[3][2] < above) hull() polyhedron(points = p, faces = [[0, 1, 2, 3]]);",
        "}",
    ]
    with open("platonic/gsd.scad", "w") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
